### ISSUE TITLE
Add species label/tag mapping

### ISSUE THREAD

**Issue by oerc0122** [oerc0122/castep_outputs#104]
Suggested by @jkshenton in #103  

> The resulting keys for the site properties get a little unwieldy with the tags and the labels - I think we should either reorganise the way these are stored/ provide some sort of aliases/ have utility functions to extract the most common bits of information needed. But that can be a in separate PR.

Possible solutions:
1. Use just general species names (w/tag?) for site properties and keep a list of labels separately which can be zipped with species props if needed
2. Create functions to pull species name info into components
3. Return a 3-uple of `(Species, Index, Label)`
4. Create a NamedTuple for `(species, index, tag, label)` defaulting to empty and `atreg_to_index` (and related parsings) return this type.

**Comment by jkshenton** [comment]
I guess that option 1 would mean changing the site properties to be lists. This is how some other libraries (e.g. ASE) deal with sites and is what I would expect.

I think that it would be nice to, at least have the option to easily extract something like:
```python
{
    'cell': 3x3 array,
    'positions': Nx3 array},
    'symbols': list of length N with standard element symbols,
}
```
with any optional site properties as Nx? lists/arrays with an appropriate key in this dictionary. e.g. forces, local magnetic moments, custom site labels, custom site species tags etc. 

any time there's a structure reported (e.g. it would be nice to be able to output a list of these for a geometry optimisation). 


However, that might go too far away from a straightforward dictionary that someone might expect from a raw parsed .castep file (?), so maybe just having a sort of user-friendly API to return these 'decorated crystal structure dictionaries' would be good. If we do it that way, then maybe option 4 would be the best, to at least standardise the raw parsed .castep dictionary .

**Comment by oerc0122** [comment]
I would probably add an extra key to the main dict for pulling out the labels, etc. 

I'm more inclined towards the `NamedTuple` approach though. I think that gives the best compromise of locality, concision and flexibility and there's a way to reconstruct it simply by adding a `__str__` method to the named tuple for `json` output. 

There's no reason we can't have multiple though. 

In terms of pulling out subsets, you might want to take a look at [`toolz`](https://toolz.readthedocs.io/en/latest/tips-and-tricks.html) which is included in e.g. `conda` or used as a dependency for a lot of stuff.

**Comment by oerc0122** [comment]
```python
import toolz

[set up pick...]

data = parse_castep_file( ... )
subset = pick(("initial_positions", "initial_cell"), data)
# subset["initial_cell"] = subset["initial_cell"]["real_lattice"] if wanted
subset["species"] = {x[0] for x in subset["initial_positions"].keys()}  # Or use [ ] for duplicates
```

But you're right that maybe some general utility functions for pulling out certain subsets might be nice. The concern is that different people might want different things and in the end it might be easier to just let them write the quick manipulation themselves.

**Comment by jkshenton** [comment]
Thanks- I'd not used `toolz` before, but it seems very handy! 

I'd be happy with the `NamedTuple` option and would be happy to help with the utility functions. I do agree that we shouldn't go overboard with these utility functions, but a couple of very common ones would make getting started with this library very easy. Plus it could act as an example of how to easily extract the information people do want - a sort of cookbook.

**Comment by oerc0122** [comment]
System with `NamedTuple` [looks like this](https://github.com/oerc0122/castep_outputs/compare/experiment-namedtuple). 

Not sure if I like it in retrospect, because while it's clean it adds an inherent non-transferability due to needing the `Atom` type

**Comment by oerc0122** [comment]
This does not preclude the use of a `dict` as the main type.

**Comment by oerc0122** [comment]
Ok. This goes much deeper and is more complicated than I'd thought (isn't it always)

magres properties don't have to be species. They will be replaced by labels if supplied. 

Geometry only uses them if not VCA in atomic positions
MD does not beyond forces

Mulliken populations can use them

As can Born charges, but there, they're stuck at the end of the line behind "ID=" rather than appended to the species 

GA uses them, but we don't parse that yet and it looks like only for recreating on child jobs

**Comment by jkshenton** [comment]
Eish yeah, these things always turn out to get complicated at some point... 

I guess standardisation like this is exactly the sort of thing that your library can help with. Again maybe having a standard raw-parsed version of the .castep file and then some getter type functions that apply the same syntax/standard as far as possible might be the way to go.

**Comment by oerc0122** [comment]
The reason why I dislike the `NamedTuple` style and the idea of a getter/setter class methods is the lack of general transferability. By avoiding specialist classes you can just load the `json`/`yaml` files directly without needing `castep_outputs` and that's one of my goals. 

Utility functions are certainly a good idea though. 

I have a feeling pulling the labels to the top may work, but why one would do that for labels, but not tags leads to inconsistencies. I'm still trying to work out how to handle this and I feel the best way is to keep it in the 
```
He:Tag [label]
```
form and provide a utility function to turn this into:
```
{'spec': 'He', 'tag': 'Tag', 'label': 'label'}
```

**Comment by oerc0122** [comment]
So I think I'm decided. 

1. Leave the labels as they are now, translating places where they're not in the "standard" form (`Sp:tag [label]`) to that form. 
2. Add some `utility` functions to pull atom names apart into these components
3. Add extra modules for `recipes` and `toolz_recipes` where we can stick in extensions to extract key components or, e.g. transform all labels into (Named)Tuples.

**Comment by oerc0122** [comment]
Closed as this issue is handled. Extension recipes will be discussed in #117
